name: lord_database 
publish_to: none 
environment: 
  sdk: '>=3.2.5 <4.0.0' 
  
dependencies: 
  firebase_core: ^2.25.3 
  firebase_database: ^10.4.4 
  flutter: 
    sdk: flutter 

dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  flutter_lints: ^2.0.0 

flutter: 
   assets: 
    - lib/src/assets/data/card.json